"""Keep Qt settings generated by tests inside pytest's temporary directory."""

from __future__ import annotations

import pytest
from PyQt6.QtCore import QSettings


@pytest.fixture(autouse=True)
def isolated_qsettings(tmp_path):
    for settings_format in (QSettings.Format.NativeFormat, QSettings.Format.IniFormat):
        for scope in (QSettings.Scope.UserScope, QSettings.Scope.SystemScope):
            directory = tmp_path / f"{settings_format.name}-{scope.name}"
            directory.mkdir()
            QSettings.setPath(settings_format, scope, str(directory))
    yield tmp_path
